name: CI
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name
    name: CI
    # This job runs on Linux
    runs-on: ubuntu-latest
    jobs:
      build:
        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-node@v1
              with:
                node-version: '10.x'
            - run: npm install
            - run: npm test
