name: Deploy
# This workflow is triggered on pushes to master to the repository.
on:  
  push:
    branches:
      - master
      - feature/deploy #remove before merge

jobs:
  job_1:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node: [ '10' ]
    name: Build node ${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm install
      - name: Executing tests
        run: npm test
      - name: Make a production build
        run: npm run build
      - name: Upload build
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build/
  job_2:
    name: Deploy
    needs: job_1
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@master
        with:
          ref: gh-pages
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: build
          path: /home/runner/work/nodes-website/nodes-website
      - name: Commit changes 
        uses: ludeeus/action-push@0.0.1
        env:
          ACTION_MAIL: ${{ secrets.EMAIL }}
          ACTION_NAME: Gabriel Chantal GitHub bot
          ACTION_BRANCH: gh-pages
          ACTION_MESSAGE: Github action deployment
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


