name: Deploy
# This workflow is triggered on pushes to master to the repository.
on:  
  push:
    branches:
      - master
      - feature/deploy #remove before merge

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node: [ '10' ]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@master
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm test
      - run: git remote set-url origin git@github.com:GabCh/nodes-website.git &&
             git config --global user.email ${{ secrets.EMAIL }} && 
             git config --global user.name ${{ secrets.NAME }} && 
             git config --global github.user ${{ secrets.USERNAME }} &&
             git config --global github.token ${{ secrets.TOKEN }} &&
             npm run deploy
