name: Deploy
# This workflow is triggered on pushes to master to the repository.
on:  
  push:
    branches:
      - master
      - feature/deploy #remove before merge

jobs:
  job_1:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node: [ '10' ]
    name: Build node ${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm install
      - name: Executing tests
        run: npm test
      - name: Make a production build
        run: npm run build
      - name: Upload build
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build/
  job_2:
    name: Deploy
    needs: job_1
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@master
        with:
          ref: gh-pages
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: build
          path: /home/runner/work/nodes-website/nodes-website
      - name: Commit changes # This is the step name that will be displayed in your runs
        uses: EndBug/add-and-commit@v1.0.0 # You can change this to use a specific version
          with: # See more info about inputs below
            author_name: Your Name
            author_email: mail@example.com
        message: "Github action deployment"
        path: ./*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

