name: Deploy
# This workflow is triggered on pushes to master to the repository.
on:  
  push:
    branches:
      - master
      - feature/deploy #remove before merge

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node: [ '10' ]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@master
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm test
      - run: git config --global user.email "you@example.com" && git config --global user.name "Your Name" && npm run deploy
